<form role="form" class="ajax row col-xs-12 col-sm-6 col-sm-offset-3" method="post" action="/user/create" onsubmit="return false">
	<h1>Sign up <small>Fast and free!</small></h1>
	<?php
	echo $this->html->div(
		array('class' => 'form-group'),
		$this->html->inputEmail(array(
			'label'       => 'Email Address',
			'name'        => 'email',
			'class'       => 'form-control input-lg email required',
			'placeholder' => 'Your email address, double check it!',
		))
	);

	echo $this->html->div(
		array('class' => 'form-group'),
		$this->html->input(array(
			'label'       => 'Username',
			'name'        => 'username',
			'class'       => 'form-control input-lg required',
			'minlength'   => 4,
			'maxlength'   => 50,
			'placeholder' => 'At least four letters or numbers',
		))
	);

	echo $this->html->div(
		array('class' => 'form-group'),
		$this->html->inputPassword(array(
			'label'       => 'Password',
			'name'        => 'password',
			'class'       => 'form-control input-lg required',
			'minlength'   => 8,
			'placeholder' => 'Use symbols along with letters and numbers',
		))
	);
	?>
	<p>By signing up you are agreeing to our <a href="/legal/terms">Terms of Service</a> and <a href="/legal/privacy">Privacy Policy</a>.</p>
	<button type="submit" class="btn btn-success btn-lg">Make it so!</button>
</form>
