<form role="form" class="row col-xs-12 col-sm-6 col-sm-offset-3" method="post">
	<h1>Sign up <small>Fast and free!</small></h1>
	<?php
	echo $this->html->div(
		array('class' => 'form-group'),
		$this->html->inputEmail(array(
			'label'       => 'Email Address',
			'name'        => 'email',
			'class'       => 'form-control input-lg email required',
			'placeholder' => 'Enter your email',
		))
	);

	echo $this->html->div(
		array('class' => 'form-group'),
		$this->html->inputPassword(array(
			'label'       => 'Password',
			'name'        => 'password',
			'class'       => 'form-control input-lg required',
			'minlength'   => 8,
			'placeholder' => 'Enter your password',
		))
	);
	?>
	<p>By signing up you are agreeing to our <a href="/legal/terms">Terms of Service</a> and <a href="/legal/privacy">Privacy Policy</a>.</p>
	<button type="submit" class="btn btn-success btn-lg">Make it so!</button>
</form>
