<div class="row">
	<div class="col-xs-12 col-sm-6">
		<h1>My Leaderboards</h1>
	</div>
	<div class="col-xs-12 col-sm-6 text-right">
		<br>
		<a class="btn btn-success" href="/leaderboard/new">New Leaderboard</a>
	</div>
</div>

<?php
if ($this->module['leaderboards'])
{
	echo '<table class="table table-striped table-responsive">';
	echo '<thead><tr><th>UID</th><th>Name</th><th>Last Activity</th><th></th></tr></thead><tbody>';

	foreach ($this->module['leaderboards'] as $uid => $updated_at)
	{
		?>
		<tr class="lead">
			<td><?php echo $uid; ?></td>
			<td><a href="/leaderboard/<?php echo $uid; ?>"><?php echo $this->module['names'][$uid]; ?></a></td>
			<td><?php echo Time::ago($updated_at); ?></td>
			<td class="text-right">
				<a class="btn btn-danger" href="/leaderboard/delete/<?php echo $uid; ?>">Delete</a>
				<a class="btn btn-primary" href="/leaderboard/edit/<?php echo $uid; ?>">Edit</a>
			</td>
		</tr>
		<?php
	}

	echo '</tbody></table>';
}
else
{
	echo '<div class="lead">You have no leaderboards, <a href="/leaderboard/new">want to create one?</a></div>';
}
?>
